import { Product, Review, SubscriptionPlan } from "./types"

export const products: Product[] = [
  // Coffee Products
  {
    id: "harar-dark-roast-500g",
    name: "Harar Dark Roast",
    description: "Our signature Ethiopian Harar beans, dark roasted to perfection. Rich, bold, and full-bodied with chocolate undertones.",
    longDescription: "Tomoca's legendary Harar coffee has been the cornerstone of our legacy since 1953. Sourced from the ancient coffee forests of Eastern Ethiopia, these 100% Arabica beans are hand-selected and expertly roasted using traditional Italian techniques. The result is a remarkably smooth, full-bodied coffee with deep chocolate notes and a lingering, satisfying finish. This is the same coffee that has made Tomoca famous throughout Addis Ababa and beyond.",
    price: 24.99,
    image: "/images/harar-dark-500g.jpg",
    images: ["/images/harar-dark-500g.jpg", "/images/harar-beans.jpg", "/images/harar-cup.jpg"],
    category: "coffee",
    subcategory: "whole-bean",
    weight: "500g",
    origin: "Harar, Ethiopia",
    roastLevel: "dark",
    flavorNotes: ["Dark Chocolate", "Roasted Nuts", "Caramel", "Full Body"],
    rating: 4.9,
    reviewCount: 847,
    inStock: true,
    isBestSeller: true,
    isSubscriptionAvailable: true,
  },
  {
    id: "harar-dark-roast-200g",
    name: "Harar Dark Roast",
    description: "Our signature Ethiopian Harar beans in a convenient 200g bag. Perfect for first-time tasters.",
    price: 12.99,
    image: "/images/harar-dark-200g.jpg",
    category: "coffee",
    subcategory: "whole-bean",
    weight: "200g",
    origin: "Harar, Ethiopia",
    roastLevel: "dark",
    flavorNotes: ["Dark Chocolate", "Roasted Nuts", "Caramel"],
    rating: 4.9,
    reviewCount: 423,
    inStock: true,
    isSubscriptionAvailable: true,
  },
  {
    id: "yirgacheffe-medium-roast",
    name: "Yirgacheffe Medium Roast",
    description: "Bright and fruity Ethiopian Yirgacheffe with floral notes. A lighter alternative to our classic Harar.",
    longDescription: "From the highlands of Yirgacheffe comes this exceptional medium roast. Known as one of the finest coffee origins in the world, Yirgacheffe beans offer a distinctly different experience from our Harar – brighter, more complex, with beautiful floral and citrus notes. Perfect for those who appreciate a more nuanced, aromatic cup.",
    price: 26.99,
    image: "/images/yirgacheffe-medium.jpg",
    category: "coffee",
    subcategory: "whole-bean",
    weight: "500g",
    origin: "Yirgacheffe, Ethiopia",
    roastLevel: "medium",
    flavorNotes: ["Jasmine", "Citrus", "Bergamot", "Honey"],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    isNew: true,
    isSubscriptionAvailable: true,
  },
  {
    id: "sidamo-light-roast",
    name: "Sidamo Light Roast",
    description: "Delicate and complex Sidamo beans, lightly roasted to preserve their unique character.",
    price: 27.99,
    image: "/images/sidamo-light.jpg",
    category: "coffee",
    subcategory: "whole-bean",
    weight: "500g",
    origin: "Sidamo, Ethiopia",
    roastLevel: "light",
    flavorNotes: ["Berry", "Wine", "Floral", "Bright Acidity"],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    isSubscriptionAvailable: true,
  },
  {
    id: "espresso-blend",
    name: "Tomoca Espresso Blend",
    description: "Our master-crafted blend designed specifically for espresso. Bold, rich, and exceptionally smooth.",
    longDescription: "Created to replicate the legendary espresso served in our Addis Ababa cafés, this blend combines the finest Ethiopian beans to create the perfect espresso experience. Deep, intense flavor with a thick crema and a finish that lingers beautifully.",
    price: 25.99,
    image: "/images/espresso-blend.jpg",
    category: "coffee",
    subcategory: "whole-bean",
    weight: "500g",
    origin: "Ethiopia Blend",
    roastLevel: "dark",
    flavorNotes: ["Espresso Crema", "Dark Cocoa", "Spice", "Velvety"],
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    isBestSeller: true,
    isSubscriptionAvailable: true,
  },
  {
    id: "ground-harar-200g",
    name: "Harar Ground Coffee",
    description: "Pre-ground Harar for convenient brewing. Medium-fine grind perfect for drip and pour-over.",
    price: 13.99,
    image: "/images/harar-ground.jpg",
    category: "coffee",
    subcategory: "ground",
    weight: "200g",
    origin: "Harar, Ethiopia",
    roastLevel: "dark",
    flavorNotes: ["Chocolate", "Nuts", "Smooth"],
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    isSubscriptionAvailable: true,
  },
  // Equipment
  {
    id: "ethiopian-jebena",
    name: "Traditional Ethiopian Jebena",
    description: "Handcrafted clay coffee pot for authentic Ethiopian coffee ceremony. Made by artisans in Addis Ababa.",
    longDescription: "The Jebena is the heart of the Ethiopian coffee ceremony – a tradition that has been practiced for centuries. Each Jebena is handcrafted by skilled artisans using traditional techniques passed down through generations. The clay pot not only brews the coffee but adds subtle earthy notes that make Ethiopian coffee ceremony unique.",
    price: 45.00,
    originalPrice: 55.00,
    image: "/images/jebena.jpg",
    category: "equipment",
    subcategory: "brewing",
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: "moka-pot-3cup",
    name: "Italian Moka Pot - 3 Cup",
    description: "Classic stovetop espresso maker. The same style used in Tomoca cafés since 1953.",
    price: 38.00,
    image: "/images/moka-pot.jpg",
    category: "equipment",
    subcategory: "brewing",
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
  },
  {
    id: "manual-grinder",
    name: "Premium Hand Coffee Grinder",
    description: "Ceramic burr hand grinder for the freshest possible grind. Consistent and quiet.",
    price: 65.00,
    image: "/images/grinder.jpg",
    category: "equipment",
    subcategory: "grinding",
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    isNew: true,
  },
  {
    id: "pour-over-set",
    name: "Pour Over Coffee Set",
    description: "Complete pour-over kit including ceramic dripper, glass carafe, and filters.",
    price: 55.00,
    image: "/images/pour-over.jpg",
    category: "equipment",
    subcategory: "brewing",
    rating: 4.8,
    reviewCount: 87,
    inStock: true,
  },
  // Accessories
  {
    id: "ethiopian-cups-set",
    name: "Ethiopian Coffee Cups Set (6)",
    description: "Traditional handleless coffee cups, handpainted with Ethiopian designs. Set of 6.",
    price: 35.00,
    image: "/images/ethiopian-cups.jpg",
    category: "accessories",
    subcategory: "cups",
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: "espresso-cups-gold",
    name: "Tomoca Espresso Cups - Gold Rim",
    description: "Elegant espresso cups with gold rim, featuring the Tomoca logo. Set of 2.",
    price: 28.00,
    image: "/images/espresso-cups.jpg",
    category: "accessories",
    subcategory: "cups",
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
  },
  {
    id: "coffee-canister",
    name: "Airtight Coffee Canister",
    description: "Keep your Tomoca beans fresh with this vacuum-sealed stainless steel canister.",
    price: 32.00,
    image: "/images/canister.jpg",
    category: "accessories",
    subcategory: "storage",
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
  },
  {
    id: "branded-apron",
    name: "Tomoca Barista Apron",
    description: "Premium cotton apron with embroidered Tomoca logo. Perfect for home baristas.",
    price: 38.00,
    image: "/images/apron.jpg",
    category: "accessories",
    subcategory: "apparel",
    rating: 4.7,
    reviewCount: 67,
    inStock: true,
  },
  // Gifts
  {
    id: "starter-gift-box",
    name: "Tomoca Starter Gift Box",
    description: "Perfect introduction to Tomoca. Includes 200g Harar beans, 2 espresso cups, and brewing guide.",
    price: 55.00,
    originalPrice: 65.00,
    image: "/images/gift-box-starter.jpg",
    category: "gifts",
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: "ceremony-gift-set",
    name: "Ethiopian Ceremony Gift Set",
    description: "Complete coffee ceremony experience: Jebena, 6 cups, 500g Harar, and frankincense.",
    price: 120.00,
    originalPrice: 145.00,
    image: "/images/ceremony-set.jpg",
    category: "gifts",
    rating: 5.0,
    reviewCount: 94,
    inStock: true,
  },
  {
    id: "coffee-lovers-bundle",
    name: "Coffee Lover's Bundle",
    description: "Three 200g bags of our finest: Harar Dark, Yirgacheffe, and Espresso Blend.",
    price: 42.00,
    originalPrice: 52.00,
    image: "/images/coffee-bundle.jpg",
    category: "gifts",
    rating: 4.8,
    reviewCount: 212,
    inStock: true,
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    author: "Marcus T.",
    rating: 5,
    date: "2024-12-15",
    content: "This is hands down the best coffee I've ever had. The Harar dark roast has this incredible chocolate finish that lingers perfectly. I've tried many Ethiopian coffees but Tomoca is in a league of its own.",
    verified: true,
  },
  {
    id: "2",
    author: "Sarah K.",
    rating: 5,
    date: "2024-12-10",
    content: "I discovered Tomoca when I visited Addis Ababa and was amazed they ship internationally! The subscription is fantastic - fresh beans every month and the quality is consistently excellent.",
    verified: true,
  },
  {
    id: "3",
    author: "David L.",
    rating: 4,
    date: "2024-12-05",
    content: "Rich, bold flavor just like I remember from my trip to Ethiopia. The only reason for 4 stars is I wish they offered a larger bag size for the subscription.",
    verified: true,
  },
  {
    id: "4",
    author: "Aisha M.",
    rating: 5,
    date: "2024-11-28",
    content: "The ceremony gift set was perfect for my parents. Everything you need for an authentic Ethiopian coffee experience. Beautiful packaging too!",
    verified: true,
  },
  {
    id: "5",
    author: "James P.",
    rating: 5,
    date: "2024-11-20",
    content: "I've been a subscriber for 6 months now. The coffee arrives fresh, the packaging is eco-friendly, and the taste is unmatched. Tomoca has ruined all other coffee for me!",
    verified: true,
  },
]

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "weekly",
    name: "Weekly Delivery",
    interval: "weekly",
    discount: 20,
    description: "Perfect for coffee enthusiasts who go through beans quickly. Fresh delivery every week.",
  },
  {
    id: "biweekly",
    name: "Every Two Weeks",
    interval: "biweekly",
    discount: 15,
    description: "Our most popular option. Fresh beans delivered every 14 days.",
  },
  {
    id: "monthly",
    name: "Monthly Delivery",
    interval: "monthly",
    discount: 10,
    description: "Great for moderate coffee drinkers. A fresh bag every month.",
  },
]

export const featuredProducts = products.filter(p => p.isBestSeller).slice(0, 4)
export const newProducts = products.filter(p => p.isNew)
export const coffeeProducts = products.filter(p => p.category === "coffee")
export const equipmentProducts = products.filter(p => p.category === "equipment")
export const accessoryProducts = products.filter(p => p.category === "accessories")
export const giftProducts = products.filter(p => p.category === "gifts")
